### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by iminsideyou** [Dev-Jahn/cs2_dma#1]
error[E0433]: failed to resolve: could not find `png` in `image`
  --> src\image.rs:13:12
   |
13 |     image::png::PngEncoder::new(&mut buffer)
   |            ^^^ could not find `png` in `image`
   |
help: consider importing this struct
   |
1  + use image::codecs::png::PngEncoder;
   |
help: if you import `PngEncoder`, refer to it directly
   |
13 -     image::png::PngEncoder::new(&mut buffer)
13 +     PngEncoder::new(&mut buffer)
   |

error[E0433]: failed to resolve: could not find `png` in `image`
  --> src\image.rs:44:12
   |
44 |     image::png::PngEncoder::new(&mut buffer)
   |            ^^^ could not find `png` in `image`
   |
help: consider importing this struct
   |
1  + use image::codecs::png::PngEncoder;
   |
help: if you import `PngEncoder`, refer to it directly
   |
44 -     image::png::PngEncoder::new(&mut buffer)
44 +     PngEncoder::new(&mut buffer)
   |

error[E0433]: failed to resolve: could not find `png` in `image`
  --> src\image.rs:63:12
   |
63 |     image::png::PngEncoder::new(&mut buffer)
   |            ^^^ could not find `png` in `image`
   |
help: consider importing this struct
   |
1  + use image::codecs::png::PngEncoder;
   |
help: if you import `PngEncoder`, refer to it directly
   |
63 -     image::png::PngEncoder::new(&mut buffer)
63 +     PngEncoder::new(&mut buffer)
   |

warning: unused import: `std::io::Cursor`
 --> src\image.rs:1:5
  |
1 | use std::io::Cursor;
  |     ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `DynamicImage`
 --> src\image.rs:3:13
  |
3 | use image::{DynamicImage, GenericImageView, ImageBuffer, imageops};
  |             ^^^^^^^^^^^^

warning: unused import: `GenericImageView`
 --> src\image.rs:3:27
  |
3 | use image::{DynamicImage, GenericImageView, ImageBuffer, imageops};
  |                           ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0433`.
warning: `cs2_dma` (bin "cs2_dma") generated 3 warnings
error: could not compile `cs2_dma` (bin "cs2_dma") due to 3 previous errors; 3 warnings emitted

**Comment by iminsideyou** [comment]
I am not too familiar with rust but I would imagine the issue is to do with relative paths not working correctly.

**Comment by Dev-Jahn** [comment]
This project has just been started so no features are implemented now.
I'll update readme after development.
